# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_uiFiles/cao.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(470, 470)
        Form.setMinimumSize(QtCore.QSize(470, 470))
        Form.setStyleSheet("")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 200, 401, 226))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_per = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_per.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton_per.setObjectName("pushButton_per")
        self.gridLayout.addWidget(self.pushButton_per, 1, 4, 1, 1)
        self.pushButton5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton5.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton5.setObjectName("pushButton5")
        self.gridLayout.addWidget(self.pushButton5, 2, 1, 1, 1)
        self.pushButton3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton3.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton3.setObjectName("pushButton3")
        self.gridLayout.addWidget(self.pushButton3, 4, 0, 1, 1)
        self.pushButton8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton8.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton8.setObjectName("pushButton8")
        self.gridLayout.addWidget(self.pushButton8, 1, 1, 1, 1)
        self.pushButton7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton7.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton7.setObjectName("pushButton7")
        self.gridLayout.addWidget(self.pushButton7, 1, 2, 1, 1)
        self.pushButton1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton1.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton1.setObjectName("pushButton1")
        self.gridLayout.addWidget(self.pushButton1, 4, 2, 1, 1)
        self.pushButton4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton4.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton4.setObjectName("pushButton4")
        self.gridLayout.addWidget(self.pushButton4, 2, 2, 1, 1)
        self.pushButton_sign1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_sign1.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton_sign1.setObjectName("pushButton_sign1")
        self.gridLayout.addWidget(self.pushButton_sign1, 1, 3, 1, 1)
        self.pushButton9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton9.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton9.setObjectName("pushButton9")
        self.gridLayout.addWidget(self.pushButton9, 1, 0, 1, 1)
        self.pushButton_sign3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_sign3.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton_sign3.setObjectName("pushButton_sign3")
        self.gridLayout.addWidget(self.pushButton_sign3, 4, 3, 1, 1)
        self.pushButton2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton2.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton2.setObjectName("pushButton2")
        self.gridLayout.addWidget(self.pushButton2, 4, 1, 1, 1)
        self.pushButton_Clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Clear.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.gridLayout.addWidget(self.pushButton_Clear, 6, 0, 1, 1)
        self.pushButton6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton6.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton6.setObjectName("pushButton6")
        self.gridLayout.addWidget(self.pushButton6, 2, 0, 1, 1)
        self.pushButton0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton0.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton0.setObjectName("pushButton0")
        self.gridLayout.addWidget(self.pushButton0, 6, 1, 1, 1)
        self.pushButton_dot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_dot.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.gridLayout.addWidget(self.pushButton_dot, 6, 2, 1, 1)
        self.pushButton_sign2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_sign2.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton_sign2.setObjectName("pushButton_sign2")
        self.gridLayout.addWidget(self.pushButton_sign2, 2, 3, 1, 1)
        self.pushButton_sign4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_sign4.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton_sign4.setObjectName("pushButton_sign4")
        self.gridLayout.addWidget(self.pushButton_sign4, 6, 3, 1, 1)
        self.pushButton_sign5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_sign5.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton_sign5.setObjectName("pushButton_sign5")
        self.gridLayout.addWidget(self.pushButton_sign5, 6, 4, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 411, 161))
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 391, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_first = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_first.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_first.setObjectName("lineEdit_first")
        self.verticalLayout.addWidget(self.lineEdit_first)
        self.lineEdit_second = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_second.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_second.setObjectName("lineEdit_second")
        self.verticalLayout.addWidget(self.lineEdit_second)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_per.setText(_translate("Form", "%"))
        self.pushButton5.setText(_translate("Form", "5"))
        self.pushButton3.setText(_translate("Form", "3"))
        self.pushButton8.setText(_translate("Form", "8"))
        self.pushButton7.setText(_translate("Form", "7"))
        self.pushButton1.setText(_translate("Form", "1"))
        self.pushButton4.setText(_translate("Form", "4"))
        self.pushButton_sign1.setText(_translate("Form", "+"))
        self.pushButton9.setText(_translate("Form", "9"))
        self.pushButton_sign3.setText(_translate("Form", "*"))
        self.pushButton2.setText(_translate("Form", "2"))
        self.pushButton_Clear.setText(_translate("Form", "C"))
        self.pushButton6.setText(_translate("Form", "6"))
        self.pushButton0.setText(_translate("Form", "0"))
        self.pushButton_dot.setText(_translate("Form", "."))
        self.pushButton_sign2.setText(_translate("Form", "-"))
        self.pushButton_sign4.setText(_translate("Form", "/"))
        self.pushButton_sign5.setText(_translate("Form", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
